/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Entidades.Cliente;
import Entidades.Mascota;
import conexion.ClienteData;
import static conexion.ClienteData.buscarClientesPorApellido;
import Vistas.PanelMascota;

import conexion.MascotaData;
import static conexion.MascotaData.listarMascotasPorCliente;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class PanelCliente extends javax.swing.JPanel {

    private DefaultTableModel modelo = new DefaultTableModel();
    private Mascota mascota = null;
    JPanel panel = null;

    public PanelCliente(JPanel panelcambio) {
        initComponents();
        panel = panelcambio;

        jTablaClientes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = jTablaClientes.getSelectedRow();
                    if (selectedRow != -1) {
                        String[] rowData = new String[jTablaClientes.getColumnCount()];
                        for (int i = 0; i < rowData.length; i++) {
                            Object value = jTablaClientes.getValueAt(selectedRow, i);
                            if (value != null) {
                                rowData[i] = value.toString();
                            } else {
                                rowData[i] = "";
                            }
                        }

                        jTnombre.setText(rowData[1]);
                        jTDocumento.setText(rowData[2]);
                        jTApellido.setText(rowData[3]);
                        jTDireccion.setText(rowData[4]);
                        jTTelefono.setText(rowData[5]);
                        jTContacto.setText(rowData[6]);
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTDocumento = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jTDireccion = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jTTelefono = new javax.swing.JTextField();
        jTContacto = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaClientes = new javax.swing.JTable();
        Salir = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jBCargar = new javax.swing.JButton();
        jBBuscarApellido = new javax.swing.JButton();
        jBModificarCliente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(880, 750));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(880, 750));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Documento");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contacto alternativo");

        jTDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTDocumentoKeyTyped(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Documento", "Apellido", "Direccion", "Telefono", "Contacto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablaClientes);
        if (jTablaClientes.getColumnModel().getColumnCount() > 0) {
            jTablaClientes.getColumnModel().getColumn(0).setResizable(false);
            jTablaClientes.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTablaClientes.getColumnModel().getColumn(1).setResizable(false);
            jTablaClientes.getColumnModel().getColumn(2).setResizable(false);
            jTablaClientes.getColumnModel().getColumn(3).setResizable(false);
            jTablaClientes.getColumnModel().getColumn(4).setResizable(false);
            jTablaClientes.getColumnModel().getColumn(5).setResizable(false);
            jTablaClientes.getColumnModel().getColumn(6).setResizable(false);
        }

        Salir.setBackground(new java.awt.Color(51, 153, 255));
        Salir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono patitas.png"))); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jBCargar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBCargar.setText("Crear Cliente");
        jBCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargarActionPerformed(evt);
            }
        });

        jBBuscarApellido.setText("Buscar ");
        jBBuscarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarApellidoActionPerformed(evt);
            }
        });

        jBModificarCliente.setText("Modificar Cliente");
        jBModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarClienteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lista de clientes");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono patitas.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono patitas.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono patitas.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono patitas.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono patitas.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(373, 373, 373))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Salir)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBCargar)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBModificarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBLimpiar)
                                .addGap(92, 92, 92)
                                .addComponent(jBEliminar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTDocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jBBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBBuscarApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(105, 105, 105))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(679, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(186, 186, 186)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(7, 7, 7)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGap(63, 63, 63)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBBuscar)
                                .addGap(9, 9, 9)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jBBuscarApellido)
                            .addComponent(jTContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBCargar)
                                .addComponent(jBLimpiar)
                                .addComponent(jBEliminar)
                                .addComponent(jBModificarCliente))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Salir)
                        .addGap(56, 56, 56))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(458, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 891, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
jBCargar.setEnabled(false);

        String dni = jTDocumento.getText();
        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El documento está vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int documento = Integer.parseInt(dni);
            Cliente clienteEncontrado = ClienteData.buscarClientePorDocumento(documento);

            if (clienteEncontrado != null) {

                jTnombre.setText(clienteEncontrado.getNombre());
                jTApellido.setText(clienteEncontrado.getApellido());
                jTDireccion.setText(clienteEncontrado.getDireccion());
                jTTelefono.setText(clienteEncontrado.getTelefono());
                jTContacto.setText(clienteEncontrado.getPersonaAlternativa());

                DefaultTableModel modeloTabla = (DefaultTableModel) jTablaClientes.getModel();
                modeloTabla.setRowCount(0);

                modeloTabla.addRow(new Object[]{
                    clienteEncontrado.getIdCliente(),
                    clienteEncontrado.getNombre(),
                    clienteEncontrado.getDocumento(),
                    clienteEncontrado.getApellido(),
                    clienteEncontrado.getDireccion(),
                    clienteEncontrado.getTelefono(),
                    clienteEncontrado.getPersonaAlternativa()
                });
            } else {
                JOptionPane.showMessageDialog(null, "Cliente no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El documento no es un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBBuscarActionPerformed


    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.setVisible(false);
        panel.removeAll();
        PanelFondo panelFondo = new PanelFondo();
        panelFondo.setBounds(0, 0, 880, 750);
        panelFondo.setVisible(true);
        panel.add(panelFondo);
        panelFondo.revalidate();
    }//GEN-LAST:event_SalirActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        jBCargar.setEnabled(true);

        jTDocumento.setText("");
        jTApellido.setText("");
        jTnombre.setText("");
        jTContacto.setText("");
        jTDireccion.setText("");
        jTTelefono.setText("");
        DefaultTableModel modelo = (DefaultTableModel) jTablaClientes.getModel();
        modelo.setRowCount(0);
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jTDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDocumentoKeyTyped
        char caracter = evt.getKeyChar();

        if (!Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTDocumentoKeyTyped


    private void jBCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargarActionPerformed
     
        String documento = jTDocumento.getText();
        String nombre = jTnombre.getText();
        String apellido = jTApellido.getText();
        String direccion = jTDireccion.getText();
        String telefono = jTTelefono.getText();
        String personaAlternativa = jTContacto.getText();

        if (documento.isEmpty() || nombre.isEmpty() || apellido.isEmpty()||direccion.isEmpty()||telefono.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Los campos obligatorios no pueden estar vacíos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (verificarSiTieneNumero(nombre) || verificarSiTieneNumero(apellido)) {
            JOptionPane.showMessageDialog(this, "Su nombre o apellido contiene numeros");
        } else {
            int idcliente = 0;
            try {
                int documentoInt = Integer.parseInt(jTDocumento.getText());
                // Crear una instancia de Cliente con los datos recopilados
                Cliente nuevoCliente = new Cliente(
                        documentoInt,
                        nombre,
                        apellido,
                        direccion,
                        telefono,
                        personaAlternativa,
                        idcliente
                );

                ClienteData.cargarCliente(nuevoCliente);
                JOptionPane.showMessageDialog(this, "Cliente agregado exitosamente");

                jTDocumento.setText("");
                jTnombre.setText("");
                jTApellido.setText("");
                jTDireccion.setText("");
                jTTelefono.setText("");
                jTContacto.setText("");

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El documento no es un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBCargarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed

        int filaSeleccionada = jTablaClientes.getSelectedRow();

        if (filaSeleccionada != -1) {

            String documentoStr = jTablaClientes.getValueAt(filaSeleccionada, 2).toString(); // Suponiendo que la columna del documento es la segunda (índice 1)
            int documento = Integer.parseInt(documentoStr);

            ClienteData.eliminarCliente(documento);

            JOptionPane.showMessageDialog(null, "Cliente eliminado correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);

            jTnombre.setText("");
            jTApellido.setText("");
            jTDocumento.setText("");
            jTDireccion.setText("");
            jTTelefono.setText("");
            jTContacto.setText("");

            DefaultTableModel modeloTabla = (DefaultTableModel) jTablaClientes.getModel();
            modeloTabla.setRowCount(0);

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente de la tabla para eliminarlo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBBuscarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarApellidoActionPerformed
        if (jTApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "debe ingresar un Apellido");
        } else {
            jBCargar.setEnabled(false);

            String apellidoBuscado = jTApellido.getText();
            if (verificarSiTieneNumero(apellidoBuscado) == true) {
                JOptionPane.showMessageDialog(this, "Su apellido contiene números");

            } else {

                ArrayList<Cliente> apellidosEncontrados = buscarClientesPorApellido(apellidoBuscado);

                DefaultTableModel modeloTabla = (DefaultTableModel) jTablaClientes.getModel();
                modeloTabla.setRowCount(0);

                for (Cliente cliente : apellidosEncontrados) {

                    modeloTabla.addRow(new Object[]{
                        cliente.getIdCliente(),
                        cliente.getNombre(),
                        cliente.getDocumento(),
                        cliente.getApellido(),
                        cliente.getDireccion(),
                        cliente.getTelefono(),
                        cliente.getPersonaAlternativa()
                    });
                }
            }
        }
    }//GEN-LAST:event_jBBuscarApellidoActionPerformed


    private void jBModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarClienteActionPerformed
        int filaSeleccionada = jTablaClientes.getSelectedRow();
        if (filaSeleccionada != -1) {
            int idCliente = Integer.parseInt(jTablaClientes.getValueAt(filaSeleccionada, 0).toString());

            int nuevoDocumento = Integer.parseInt(jTDocumento.getText());
            String nuevoNombre = jTnombre.getText();
            String nuevoApellido = jTApellido.getText();
            String nuevaDireccion = jTDireccion.getText();
            String nuevoTelefono = jTTelefono.getText();
            String nuevoContacto = jTContacto.getText();
            if (jTnombre.getText().isEmpty() || jTApellido.getText().isEmpty() || jTDireccion.getText().isEmpty() || jTTelefono.getText().isEmpty() || jTContacto.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "debe completar todos los campos");
            } else {
                if (verificarSiTieneNumero(nuevoNombre) == true || verificarSiTieneNumero(nuevoApellido) == true) {
                    JOptionPane.showMessageDialog(this, "Su nombre o apellido contiene números");

                } else {
                    Cliente clienteModificado = new Cliente(nuevoDocumento, nuevoNombre, nuevoApellido, nuevaDireccion, nuevoTelefono, nuevoContacto, idCliente);

                    ClienteData.modificarCliente(clienteModificado);

                    JOptionPane.showMessageDialog(null, "Cliente modificado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                    DefaultTableModel modelo = (DefaultTableModel) jTablaClientes.getModel();
                    modelo.setRowCount(0);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.");
        }

    }//GEN-LAST:event_jBModificarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBBuscarApellido;
    private javax.swing.JButton jBCargar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBModificarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTContacto;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTDocumento;
    private javax.swing.JTextField jTTelefono;
    private javax.swing.JTable jTablaClientes;
    private javax.swing.JTextField jTnombre;
    // End of variables declaration//GEN-END:variables
private boolean verificarSiTieneNumero(String valor) {

        int largoValor = valor.length();

        boolean bandera1 = false;

        for (int i = 0; i < largoValor; i++) {
            bandera1 = false;
            if (Character.isDigit(valor.charAt(i))) {

                bandera1 = true;
                break;
            }

        }
        return bandera1;
    }
}
